### ISSUE TITLE
labels fails to build with GHC 8.2 RC3

### ISSUE THREAD

**Issue by jchia** [chrisdone/labels#8]
I tried building `labels` with GHC 8.2 RC3 using this `stack.yaml`:
```
resolver: nightly-2017-07-20
compiler: ghc-8.2.0.20170704
compiler-check: match-exact
packages:
- labels
```

but got this error:
```
$ stack build labels
labels-0.3.2: build (lib)
Preprocessing library for labels-0.3.2..
Building library for labels-0.3.2..
[1 of 2] Compiling Labels.Internal  ( src/Labels/Internal.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.0.0/build/Labels/Internal.o )

/home/jchia/gh/labels/labels/src/Labels/Internal.hs:66:5: error:
    • Couldn't match expected type ‘Proxy l'’
                  with actual type ‘p0 -> Proxy t0’
    • The equation(s) for ‘fromLabel’ have one argument,
      but its type ‘Proxy l'’ has none
      In the instance declaration for ‘IsLabel l (Proxy l')’
    • Relevant bindings include
        fromLabel :: Proxy l' (bound at src/Labels/Internal.hs:66:5)
   |
66 |     fromLabel _ = Proxy
   |     ^^^^^^^^^^^^^^^^^^^

--  While building package labels-0.3.2 using:
      /home/jchia/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.0.0_ghc-8.2.0.20170704 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.0.0 build lib:labels --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

I suspect it's because of GHC 8.2 changes to `OverloadedLabels`.

**Comment by chrisdone** [comment]
Should be a straight-forward change. I'll fix it when it's officially released.

**Comment by DanBurton** [comment]
Bump. Issue confirmed with official release, saw the same error message on the Stackage build server.

```
[1 of 2] Compiling Labels.Internal  ( src/Labels/Internal.hs, dist/build/Labels/Internal.o )

src/Labels/Internal.hs:66:5: error:
    • Couldn't match expected type ‘Proxy l'’
                  with actual type ‘p0 -> Proxy t0’
    • The equation(s) for ‘fromLabel’ have one argument,
      but its type ‘Proxy l'’ has none
      In the instance declaration for ‘IsLabel l (Proxy l')’
    • Relevant bindings include
        fromLabel :: Proxy l' (bound at src/Labels/Internal.hs:66:5)
   |
66 |     fromLabel _ = Proxy
   |     ^^^^^^^^^^^^^^^^^^^
```

**Comment by jchia** [comment]
Would you mind putting the latest version on hackage and stack?
